# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68cc46abea98b288b610b1a7966ab561cf92455937e9ef3239495802dc946dfc314c4232ffe48d53e850fae589b007fe13635c3ab117a8ebede207a88ff3f974

test:
  secret_key_base: b6072e85278481705a2644672d9da552f5d4c63d484f0cc939623508bf844ffd9811d33fa0fbb0cef5224b35a0bd74519fae3522818831ff1ec4379957b9ebd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
